# 
# policy_path: "/home/csl/IsaacLab/logs/rsl_rl/bipedal/2024-11-22_09-19-31/exported/policy.pt"
policy_path:  "/home/csl/crazydog/crazydog_ws/src/rl_control/rl_control/model/2024-12-26_13-37-36/exported/policy.pt"
xml_path: "/home/csl/robot_model/crazydog_urdf/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [50, 50, 50, 50, 0, 0]
kds: [3.5, 3.5, 3.5, 3.5, 0.3, 0.3]

default_angles: [1.27, 1.27, -2.127, -2.127, 0, 0]

lin_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0   
dof_vel_scale: 1.0
action_scale: 1.0
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 6
num_obs: 28

cmd_init: [0.0, 0, 0]