# 
policy_path: "/home/csl/robot_model/bi_urdf/model/2024-12-20_11-19-56/exported/policy.pt"
# policy_path: "/home/csl/robot_model/bi_urdf/model/2024-12-23_22-57-27/exported/policy.pt"
# policy_path: "/home/csl/crazydog/crazydog_ws/src/rl_control/rl_control/model/2024-12-27_11-58-27/exported/policy.pt"
xml_path: "/home/csl/robot_model/bi_urdf/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [0, 0]
kds: [0.1, 0.1]

default_angles: [0, 0]

lin_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0   
dof_vel_scale: 1.0
action_scale: 1.0
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 2
num_obs: 16

cmd_init: [0.0, 0, 0]