# 
policy_path:  "pre_train/isaaclab/2025-03-24_20-26-04/exported/policy.pt"
xml_path: "scene_lab.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

# kps: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
kds: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
# kps: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
# kds: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

# kps: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
kps: [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]
# kds: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

default_angles: [0.1, -0.1, 0.1, -0.1, 0.785, 0.785, -0.785, -0.785, -1.57, -1.57, 1.57, 1.57]
# initial_pos: [-0.3, 0.3, -0.3, 0.3, 0.785, 0.785, -0.785, -0.785, -1.57, -1.57, 1.57, 1.57]


lin_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.2
cmd_scale: [1.0, 1.0, 1.0]
num_actions: 12
num_obs: 48

animation: False  # change num_obs to 49 if True
max_step: 83

cmd_init: [0.0, 0.0, 0.5]