# 
policy_path:  "pre_train/isaaclab/2025-02-24_11-49-51/exported/policy.pt"
# policy_path: "pre_train/isaaclab/2025-02-24_03-28-10/exported/policy.pt"
xml_path: "scene_lab.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [0.1, -0.1, -0.1, 0.1, 0.785, 0.785, -0.785, -0.785, -1.57, -1.57, 1.57, 1.57]

lin_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.2
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 48

cmd_init: [0, 0, 0]